language: rust

os:
  - linux
  - osx

env:
  - ARCH=i686
  - ARCH=x86_64

before_script:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
  - export PATH=~/.cargo/bin:$PATH
  - if [[ $TRAVIS_OS_NAME == "linux" && $ARCH == "x86_64" ]]; then rustup target add x86_64-unknown-linux-musl; fi
  - if [[ $TRAVIS_OS_NAME == "linux" && $ARCH == "i686"   ]]; then rustup target add i686-unknown-linux-musl;   fi
  - if [[ $TRAVIS_OS_NAME == "osx"   && $ARCH == "i686"   ]]; then rustup target add i686-apple-darwin;         fi

script:
  - if [[ $TRAVIS_OS_NAME == "osx"   && $ARCH == "x86_64" ]]; then cargo build --release --target=x86_64-apple-darwin;       fi
  - if [[ $TRAVIS_OS_NAME == "osx"   && $ARCH == "i686"   ]]; then cargo build --release --target=i686-apple-darwin;         fi
  - if [[ $TRAVIS_OS_NAME == "linux" && $ARCH == "x86_64" ]]; then cargo build --release --target=x86_64-unknown-linux-musl; fi