version: 1.0.{build}

environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
  - TARGET: i686-pc-windows-msvc
  - TARGET: x86_64-pc-windows-gnu
  - TARGET: i686-pc-windows-gnu
install:
  - appveyor-retry curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - appveyor-retry rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -vV
  - cargo -vV
build: false
test_script:
  - appveyor-retry cargo build --verbose
  - cargo test --verbose
branches:
  except:
  - staging.tmp
